language: lisp

env:
  matrix:
    - LISP=sbcl
    - LISP=ecl

install:
  - curl -L https://github.com/luismbo/cl-travis/raw/master/install.sh | bash

script:
  - cl -e "(ql:quickload :cl-point-bot) (cl-point-bot.tests::run! 'cl-point-bot.tests::cl-point-bot-suite)"
